server:
  servlet:
    context-path: /supershop

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/geekbrains
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1

  thymeleaf:
    cache: false